# Generated by Django 2.2.7 on 2019-11-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20191127_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_seat',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
