# Generated by Django 2.2.7 on 2019-11-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20191127_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='password',
            field=models.CharField(default='123456', max_length=50),
        ),
    ]
