# Generated by Django 2.2.7 on 2019-11-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_car_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate_num',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
