# Generated by Django 2.2.7 on 2019-12-07 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20191127_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_odo', models.URLField()),
                ('image_drive', models.URLField()),
                ('image_pass', models.URLField()),
                ('image_plate', models.URLField()),
                ('date', models.DateField()),
                ('aproved', models.BooleanField(blank=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Car')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Report')),
            ],
        ),
    ]
