# Generated by Django 2.2.7 on 2019-12-08 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_reportimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='note',
        ),
        migrations.RemoveField(
            model_name='report',
            name='start_date',
        ),
    ]
