# Generated by Django 2.2.7 on 2019-12-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_auto_20191208_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportimage',
            name='aproved',
        ),
        migrations.AddField(
            model_name='reportimage',
            name='drive_aproved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='reportimage',
            name='odo_aproved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='reportimage',
            name='pass_aproved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='reportimage',
            name='plate_aproved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
