# Generated by Django 2.2.7 on 2019-12-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_auto_20191208_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimage',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='image_drive',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='image_odo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='image_pass',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='image_plate',
            field=models.URLField(blank=True),
        ),
    ]
