# Generated by Django 2.2.7 on 2019-12-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_auto_20191208_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimage',
            name='image_drive',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='image_odo',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='image_pass',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='image_plate',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
