# Generated by Django 2.2.7 on 2019-12-19 08:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0011_auto_20191219_0825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCampaig',
            new_name='UserCampaign',
        ),
    ]
