# Generated by Django 2.2.7 on 2019-12-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_auto_20191219_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='carkpi',
            name='impression',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True),
        ),
    ]
